# Generated by Django 4.0.1 on 2022-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Null', max_length=100)),
                ('price', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
